report: report/week.44.pdf
report/week.44.pdf: report/week.44.tex
	pdflatex -output-directory report/tmp report/week.44.tex 
	pdflatex -output-directory report/tmp report/week.44.tex #yes yes, use texmake or whatevs
	mv report/tmp/week.44.pdf report/week.44.pdf
